import React from 'react';
import { AlertCircle, HeartHandshake } from 'lucide-react';

export const DisclaimerPage: React.FC = () => {
  return (
    <div className="w-full max-w-4xl mx-auto px-4 py-8 md:py-12">
      <div className="bg-white rounded-3xl p-6 sm:p-10 md:p-12 shadow-lg shadow-rose-100/50 border border-rose-100 text-slate-700 leading-relaxed space-y-6">
        <div className="border-b border-rose-100 pb-6">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-amber-50 text-amber-700 rounded-full text-xs font-semibold mb-3 border border-amber-200">
            <AlertCircle className="w-3.5 h-3.5 text-amber-600" />
            <span>Entertainment Advisory</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-800 tracking-tight">
            Entertainment Disclaimer
          </h1>
          <p className="text-xs text-slate-400 mt-2">
            Please Read Carefully
          </p>
        </div>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 font-display">
            1. Solely for Entertainment &amp; Amusement
          </h2>
          <p className="text-sm">
            All quizzes, calculators, character assignments, compatibility ratings, and interactive pranks on <strong>FluffyHearts</strong> are created entirely for recreational, comedic, and entertainment purposes.
          </p>
          <p className="text-sm">
            The results generated by our Love Compatibility Quiz, Animal Personality Quiz, and Friendzone Diagnosis are calculated by playful, lighthearted algorithms intended to prompt smiles, friendly banter, and shared laughter between friends and loved ones.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 font-display">
            2. Not Professional Relationship or Psychological Counsel
          </h2>
          <p className="text-sm">
            Content provided on this website does not constitute, and should never be interpreted as, professional marriage counseling, psychological advice, medical evaluation, or relationship therapy. Human emotions and partnerships are multifaceted, and an online quiz should never replace sincere interpersonal communication or guidance from licensed mental health professionals.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 font-display">
            3. Playful Prank Disclosure
          </h2>
          <p className="text-sm">
            The escaping "No" button interaction and joke confession punchline (<em>"Yrr me to tumhe dost smjhta tha"</em>) are designed as gentle, harmless internet humor. They are meant to be shared in good faith with consenting friends and crushes who appreciate lighthearted jokes.
          </p>
        </section>

        <div className="p-5 rounded-2xl bg-amber-50/70 border border-amber-200/80 flex items-start gap-3">
          <HeartHandshake className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
          <p className="text-xs text-amber-800 leading-relaxed">
            By interacting with our games and quizzes, you acknowledge and agree that your participation is voluntary and that FluffyHearts is not liable for any personal decisions, impressions, or emotional interpretations arising from playful quiz outcomes.
          </p>
        </div>
      </div>
    </div>
  );
};
